<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Hackathon-Demo" duration-ms="45805" started-at="2018-10-25T10:09:28Z" finished-at="2018-10-25T10:10:14Z">
    <groups>
    </groups>
    <test name="Write new post" duration-ms="45805" started-at="2018-10-25T10:09:28Z" finished-at="2018-10-25T10:10:14Z">
      <class name="hackathon.demo.TestClass">
        <test-method status="PASS" signature="LoginSuccessTC()[pri:0, instance:hackathon.demo.TestClass@47f6473]" name="LoginSuccessTC" duration-ms="30962" started-at="2018-10-25T15:39:38Z" description="Valid login scenerio with authenticate username &amp; password" finished-at="2018-10-25T15:40:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginSuccessTC -->
        <test-method status="FAIL" signature="LoginFailTC()[pri:0, instance:hackathon.demo.TestClass@47f6473]" name="LoginFailTC" duration-ms="3472" started-at="2018-10-25T15:40:09Z" description="Invalid login scenerio with wrong username &amp; password" finished-at="2018-10-25T15:40:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Nielsen Studio] but found [Nielsen Studio » Log in]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Nielsen Studio] but found [Nielsen Studio » Log in]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at hackathon.demo.TestClass.LoginFailTC(TestClass.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginFailTC -->
      </class> <!-- hackathon.demo.TestClass -->
    </test> <!-- Write new post -->
  </suite> <!-- Hackathon-Demo -->
</testng-results>
